### ISSUE TITLE
Vector Indexer Implimenting, "Index Expression must be constant".

### ISSUE THREAD

**Issue by occar421** [thefiddler/ShaderTK#2]
From testing with [GLSL Sandbox](http://glslsandbox.com/), writing below causes " '[]':Index Expression must be constant"

``` glsl
int index = 1;
float y = position[index];
//OK: float y = position[1];
```

normal C# syntax can't prevent this.  
So I have some ideas that property(.l0l .l1l) instead of indexer, custom attribute for checking, or ignoring.

PS: validating by ShaderTK befere compiling to GLSL is needed, I think.

**Comment by thefiddler** [comment]
I think GLSL allows this on recent core/desktop versions. I'm not sure about ES, but in WebGL this is only allowed for uniform arrays.

A validation stage with portability warnings would be nice but it could get really complicated fast. Essentially, this would require to implement a GLSL parser, which is far from trivial.

A more feasible approach might be to validate the generated GLSL using the [reference compiler](http://www.khronos.org/opengles/sdk/tools/Reference-Compiler/).

**Comment by occar421** [comment]
I missed that it is WebGL, sorry.

It was ok with reference compiler, so I just make #3.
